export const SponsorTitle = "Sponsors"
export const Sponsor1Desc = "Zhongyi Fashion Co., Ltd. (Hong Kong) is a comprehensive cultural enterprise with core business of undertaking large-scale cultural events. The core members of the company are from the circle of fashion, film, advertising and other cultural elites from all walks of life. Thus it has all-round event organization capability from planning, implementation and investment to promotion. Its rich resources of collection of top brands around the world and major well-known media both at home and abroad adequately guarantee to provide for large-scale cultural activities and events with the most professional and most high-end one-stop solution.";
export const Sponsor1Chi = "中藝時尚有限公司（香港)";
export const Sponsor1Name = "Zhongyi Fashion Co., Ltd. (Hong Kong)";

export const Sponsor2Desc = 'Since its establishment in 2004 the company has always been dedicated to the creation and development of film and television arts with the purpose of carrying forward national culture and local traditional arts with various of carriers of film and television. It carefully create good theme and wholeheartedly plan quality competitive products that broadens the brands and influence. It produce, create, plan, distribute and participate in working with project including TV series: “Flying Indus’”  “Give me a Reason for Love” “Long Whisper” “New Police” “Night of Amazing”“Battlefield Bloom” “Top Secret 1950”“Anti-Japanese Warrior” “Quit Smoking” “Pirate Rescue Team” “Peak Song” “Bloody Coordinates". Network drama:  "Trivial" "Gray" "Frame Love" "Nanke Dream" “T Station". Others:  "Stadium " "Speed Camp" "Beacon" "Car and Movie " "Woman Car Gang" "My Car My Way" and 13 others. Exhibition Events: Planning and implementation of the 2008 International Auto Show, Chery Million Release, Mercedes-Benz, BMW, Audi and various car market activities, Shanghai Film Festival 2011, Island Music Festival and others.';
export const Sponsor2Chi = "北京龙世·盛方国际文化有限公司";
export const Sponsor2Name = "Beijing F-W (Flourishing World) international Culture Co. Ltd.";
export const CollectiveSponsorText = "Since 2017, both companies have established long-term strategic cooperation with Miss Tourism Asia Organizing Committee. Together they participated in the organization of Miss Tourism Asia event in Ningxia it has become the best-known annual cultural event due to its good grasp of fashion culture and extensive experience in operating large-scale events, it also bring the brand “Miss Tourism Asia” wide range of visibility and publicity at home and good public response.";
